Repository RBusarow/Tangle, pull requests merged in 2022-08, with the labels that each got.

#531 make benchmarks results Windows-friendly
  .github/workflows/ci.yml
  benchmarks/profile.sh
  benchmarks/reports/profile_10-03-2021_23-42/benchmark.csv
  benchmarks/reports/profile_10-03-2021_23-42/benchmark.html
  benchmarks/reports/profile_10-03-2021_23-42/profile.log
  benchmarks/reports/profile_10-08-2021_12-58/benchmark.csv
  benchmarks/reports/profile_10-08-2021_12-58/benchmark.html
  benchmarks/reports/profile_10-08-2021_12-58/profile.log
  build.gradle.kts
  buildSrc/src/main/kotlin/benchmarks.gradle.kts
Labels: automerge

#536 use `gradle-build-action` for caching in instrumented tests and add AVD caching
  .github/workflows/ci.yml
Labels: automerge, chore

#539 revert paging-compose to 1.0.0-alpha14
  .github/workflows/ci.yml
  gradle/libs.versions.toml
Labels: dependencies, automerge

#527 Fragment lookup for compose ViewModelStoreOwner fix
  tangle-viewmodel-compose/src/main/kotlin/tangle/viewmodel/compose/tangleViewModel.kt
Labels: automerge, bugfix

#542 add caching to the website publish job and increase its memory
  .github/workflows/website.yml
Labels: automerge
