Repository RBusarow/Tangle, pull requests merged in 2022-07, with the labels that each got.

#456 automatically publish snapshots on merge
  .github/workflows/ci.yml
  .github/workflows/publish-snapshot.yml
Labels: automerge

#459 remove the `-q` switch from ktlintCheck in CI
  .github/workflows/ci.yml
Labels: automerge

#477 add dependency-guard plugin and baselines
  .github/workflows/ci.yml
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/dependency-guard.gradle.kts
  buildSrc/src/main/kotlin/published.gradle.kts
  gradle/libs.versions.toml
  tangle-api/dependencies/runtimeClasspath.txt
  tangle-compiler/dependencies/runtimeClasspath.txt
  tangle-fragment-api/dependencies/releaseRuntimeClasspath.txt
  tangle-fragment-compiler/dependencies/runtimeClasspath.txt
  tangle-gradle-plugin/dependencies/runtimeClasspath.txt
  tangle-viewmodel-activity/dependencies/releaseRuntimeClasspath.txt
  tangle-viewmodel-api/dependencies/releaseRuntimeClasspath.txt
  tangle-viewmodel-compiler/dependencies/runtimeClasspath.txt
  tangle-viewmodel-compose/dependencies/releaseRuntimeClasspath.txt
  tangle-viewmodel-fragment/dependencies/releaseRuntimeClasspath.txt
  tangle-work-api/dependencies/releaseRuntimeClasspath.txt
  tangle-work-compiler/dependencies/runtimeClasspath.txt
Labels: automerge

#479 clean up runtime classpaths for published modules
  build.gradle.kts
  tangle-api/build.gradle.kts
  tangle-api/dependencies/runtimeClasspath.txt
  tangle-compiler/build.gradle.kts
  tangle-fragment-api/build.gradle.kts
  tangle-fragment-api/dependencies/releaseRuntimeClasspath.txt
  tangle-fragment-compiler/build.gradle.kts
  tangle-gradle-plugin/build.gradle.kts
  tangle-gradle-plugin/dependencies/runtimeClasspath.txt
  tangle-viewmodel-activity/build.gradle.kts
  tangle-viewmodel-activity/dependencies/releaseRuntimeClasspath.txt
  tangle-viewmodel-api/build.gradle.kts
  tangle-viewmodel-compiler/build.gradle.kts
  tangle-viewmodel-compose/build.gradle.kts
  tangle-viewmodel-compose/dependencies/releaseRuntimeClasspath.txt
  tangle-viewmodel-fragment/build.gradle.kts
  tangle-viewmodel-fragment/dependencies/releaseRuntimeClasspath.txt
  tangle-work-api/build.gradle.kts
Labels: automerge

#486 fixing the website build
  .github/workflows/ci.yml
  tangle-viewmodel-activity/src/main/kotlin/tangle/viewmodel/activity/tangleViewModel.kt
  website/docusaurus.config.js
  website/package.json
  website/src/css/custom.css
  website/src/pages/styles.module.css
  website/yarn.lock
Labels: automerge

#490 fix compose instrumented test flakes
  renovate.json
  sample/app/src/androidTest/kotlin/tangle/sample/app/support/retry.kt
  sample/app/src/androidTest/kotlin/tangle/sample/app/tests/ComposeActivitiesIntegrationTest.kt
  sample/app/src/androidTest/kotlin/tangle/sample/app/tests/ComposeFragmentsIntegrationTest.kt
  tangle-api/src/main/kotlin/tangle/inject/TangleGraph.kt
Labels: automerge

#489 fix javadoc generation in release builds
  buildSrc/src/main/kotlin/dokka.gradle.kts
  buildSrc/src/main/kotlin/knit.gradle.kts
  buildSrc/src/main/kotlin/published.gradle.kts
  gradle/libs.versions.toml
Labels: automerge

#501 don't skip the dependency-guard job for Renovate in CI
  .github/workflows/ci.yml
Labels: automerge

#502 remove `ref` values from `actions/checkout` in ci unless it's in a "used by main repo" job
  .github/workflows/ci.yml
Labels: automerge, chore

#420 Allow `Fragment::arg` with nullable parameters.
  tangle-fragment-api/api/tangle-fragment-api.api
  tangle-fragment-api/build.gradle.kts
  tangle-fragment-api/src/main/kotlin/tangle/fragment/arg.kt
  tangle-fragment-api/src/test/kotlin/tangle/fragment/ArgOrNullTest.kt
  tangle-fragment-api/src/test/kotlin/tangle/fragment/ArgTest.kt
  tangle-fragment-api/src/test/kotlin/tangle/fragment/samples/ArgSampleFragment.kt
Labels: automerge

#507 make the `versionDocs` task depend upon `yarnInstall`
  buildSrc/src/main/kotlin/website.gradle.kts
  release.sh
Labels: automerge

#508 create release 0.15.0
  CHANGELOG.md
  buildSrc/src/main/kotlin/tangle/builds/Versions.kt
  website/src/pages/CHANGELOG.md
  website/versioned_docs/version-0.15.0/benchmarks.md
  website/versioned_docs/version-0.15.0/configuration.mdx
  website/versioned_docs/version-0.15.0/extending-anvil.md
  website/versioned_docs/version-0.15.0/fragments/bundles.md
  website/versioned_docs/version-0.15.0/fragments/fragments.mdx
  website/versioned_docs/version-0.15.0/gradle-plugin.mdx
  website/versioned_docs/version-0.15.0/member-injection.md
  website/versioned_docs/version-0.15.0/viewModels/compose.md
  website/versioned_docs/version-0.15.0/viewModels/savedStateHandle.md
  website/versioned_docs/version-0.15.0/viewModels/viewModels.md
  website/versioned_docs/version-0.15.0/workManager/workManager.md
  website/versioned_sidebars/version-0.15.0-sidebars.json
  website/versions.json
Labels: documentation, automerge
